### ISSUE TITLE
object.size() vs obj_size()

### ISSUE THREAD

**Issue by amrrs** [r-lib/lobstr#21]
Sorry I couldn't understand the difference from the documentation

```
library(lobstr)
x <- 1:1e6
y <- list(x, x, x)
ref(y)
#> █ [1:0x7fee181b95e8] <list> 
#> ├─[2:0x7fee142b72a8] <int> 
#> ├─[2:0x7fee142b72a8] 
#> └─[2:0x7fee142b72a8]

object.size(x)
#> 4000048 bytes
obj_size(x)
#> 680 B


object.size(y)
#> 12000224 bytes
obj_size(y)
#> 760 B


ref(x)
#> [1:0x7fee142b72a8] <int>
ref(y)
#> █ [1:0x7fee181b95e8] <list> 
#> ├─[2:0x7fee142b72a8] <int> 
#> ├─[2:0x7fee142b72a8] 
#> └─[2:0x7fee142b72a8]
```

Why is such a huge difference between the two and also why is object.size() doubling the size of y but obj_size doesn't - does it mean the memory allocation has been doubled?

**Comment by hadley** [comment]
This is because in R 3.5 `1:n` is represented as a special object type (ALTREP) that only requires storing   1 and n, so is actually very small. `object.size()` doesn't take this into account.

Similarly, `object.size()` doesn't take into account that `y` consists of 3 references to the same object, so it adds the (incorrect) size of `x` three times.

**Comment by amrrs** [comment]
Thanks for the explanation. So I understand, `obj_size()` is more accurate and relevant in knowing the memory allocation size while `object.size()` calculates size literally without considering references and other such nuances into account.

**Comment by hadley** [comment]
Correct.
