### ISSUE TITLE
Cannot ref shiny reactiveValues

### ISSUE THREAD

**Issue by dipterix** [r-lib/lobstr#30]
`ref` method will call `as.list.reactiveValues` for shiny reactive values (such as session), which causes errors.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by dipterix** [comment]
Can't use `reprex` for the case 1 because it runs forever. 

Case 1:

```r
# devtools::install_github('beauchamplab/rave@rave-fir')
  library(rave)
  library(lobstr)
  # rave::download_subject_data('https://s3-us-west-2.amazonaws.com/rave-demo-subject/sfn-demo/data-large.zip')
  m = unlist(load_modules())[[3]]
  init_app(m, test.mode = T)
  ref(m)
```

Error message:

```
'as.list.reactivevalues' is deprecated. Use reactiveValuesToList instead.
Please see ?reactiveValuesToList for more information.
Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
```


Second case doesn't go well with `reprex` as well since the shiny app didn't launch.


``` r
suppressPackageStartupMessages(library(shiny))
env = new.env()

shinyApp(fluidPage(actionButton('asd',' ')), server = function(input,output,session){
  local_data = reactiveValues(a=1)
  
  env$sess = session
  stopApp()
})
```



<div class="muted well" style="width: 100% ; height: 400px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;">

Shiny applications not supported in static R Markdown documents

</div>



``` r

lobstr::ref(env$sess)
#> [1:0x7fada201e2e0] <NULL>
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

If I ran without `reprex`, then the error message is:

```r
>   lobstr::ref(env$sess)
Error in is.character(lhs) : 
  C stack usage  7970736 is too close to the limit
Error during wrapup: C stack usage  7969856 is too close to the limit
```

**Comment by hadley** [comment]
Can you please give me some snippet off code to run that doesn't require installing other packages or installing large data? It should be possible to make a very small shiny app to demonstrate the problem.

**Comment by yutannihilation** [comment]
I can reproduce the issue with the code above, though the error message is different now.

```
> lobstr::ref(env$sess)
Error in is.character(lhs) : node stack overflow
```

This part might be done with `shiny:::ShinySession$new(ws)`, but I'm yet to find what `ws` I should pass...

```r
  env$sess = session
```

**Comment by hadley** [comment]
@jcheng5 should be able to help you figure it out

**Comment by yutannihilation** [comment]
> I can reproduce the issue with the code above

Sorry, I just looked at the second issue... 🙄 

For the first case, @jcheng5 suggested (thanks!) we can use `options(shiny.suppressMissingContextError=TRUE)` to suppress the error.

For the second case, it seems there's a ciruclation of reference:

``` r
> unclass(env$sess$.__enclos_env__)
<environment: 0x00000197c79482c0>
> unclass(env$sess$.__enclos_env__$self$.__enclos_env__)
<environment: 0x00000197c79482c0>
```

**Comment by yutannihilation** [comment]
> For the second case, it seems there's a ciruclation of reference

Sorry, this is not the core of the problem, it seems `package_version` (`env$sess$request$httpuv.version`) is the problem:

``` r
> lobstr::ref(package_version("0.0.1"))
Error in is.character(lhs) : node stack overflow
```

**Comment by jcheng5** [comment]
I'm missing some context here but if you do decide to set the `shiny.suppressMissingContextError` option, please make sure to restore its previous value when you're done.

**Comment by yutannihilation** [comment]
Yes, I'd like to (but maybe not today...).

**Comment by hadley** [comment]
No problems, the most important thing is the reprex 😄

**Comment by yutannihilation** [comment]
It seems you are right; `ref_tree()` is applied infinitely here because `lapply(<package_version>, f)` passes the newly generated `package_version`, not its elements, to `f()`.

https://github.com/r-lib/lobstr/blob/9fcf6429e52e7caf367b58663219726b757dff07/R/ref.R#L57

The problem is `[[.numeric_version()` creates a new object, so it never matches the addresses in `seen`.

``` r
library(lobstr)

x <- package_version("1.0.0")

obj_addr(x)
#> [1] "0x156f7138"

obj_addr(x[[1]])
#> [1] "0x17f49378"

obj_addr(x[[1]])
#> [1] "0x17f6d648"
```

<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Using `.subset2()` might be an idea, but I think it's not always possible to know the "correct" length of the object to generate indices, because `length()` might tell us some wierd value.

Instead, how about `unclass()` in all these recursive cases? Since we are looking into the underlying structure, we don't need custom classes and methods. This means we can avoid calling such methods as `as.list.reactiveValues()`, so I feel this fix is more general.

https://github.com/r-lib/lobstr/blob/9fcf6429e52e7caf367b58663219726b757dff07/R/ref.R#L55-L62

If this looks OK, I'll create a PR.

**Comment by hadley** [comment]
Yeah, that sounds right to me.

**Comment by yutannihilation** [comment]
Thanks, I created #36.

BTW, I didn't know environments cannot be unclassed...

``` r
e <- structure(new.env(), class = "foo")
class(e)
#> [1] "foo"
unclass(e)
#> Error in unclass(e): cannot unclass an environment
```

<sup>Created on 2019-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
